name: Testing workflow. Jonnius's version

on:                  # events that triggers the workflow
  push:              # pushing LOCAL? commits
    branches:        # - github-actions-tutorial # monitors only 1
      [ master, github-actions-tutorial ] 
  
  pull_request:
    branches:        # [ master ] # was originally
      [ master, github-actions-tutorial ] 
  
  workflow_call:     # indicates that this workflow can be invoked by another one
  # Another workflow can trigger this testing workflow as one of its job steps,  ensuring it passes BEFORE moving on to next steps.
  # Github-username/repo/path/to/workflow@version
  # - uses: realpython/reader/.github/workflows/test.yml@master
  # @master tells the extarnal workflow that it wants to use the version of the testing workflow from the master branch

  workflow_dispatch: # dispatch the workflow MANUALLY
# used to rerun a workflow failed for reasons unrelated to code changes, e.g. an expired API key

jobs:
  testing:
    strategy:  # lets use variables in a SINGLE JOB definition to automatically create MULTIPLE JOB RUNS that are based on the combinations of the variables.
      matrix:  # lets access any variable defined as part of the matrix with the dot (.) syntax, f.ex. matrix.python-version
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
        os: [ubuntu-latest, windows-latest]
    runs-on: ubuntu-latest # could use the dot notation to access the os variable defined in the matrix with matrix.os.

    steps: 
      - uses: actions/checkout@v4 # Selects an action to run as part of a step

      - name: Set up Python ${{ matrix.python-version }} # isn’t required but helps identify which Python version failed 
        uses : actions/setup-python@v5
        with: 
          python-version: ${{ matrix.python-version }} 
          cache : "pip"